hoursToMonitor: 9
delayTimeInMinutes: 0.01
flows:
  - flow:
      type : json
      name : authenticacion
      steps:
        - step:
            name: "auth"
            caller: src.infrastructure.callers.authorization_requests_caller
