hoursToMonitor: 9
delayTimeInMinutes: 1
flows:
  - flow:
      name : authenticacion
      steps:
        - step:
            name: "auth-sf"
            caller: src.infrastructure.callers.authorization_requests.get_request_with_sf
        - step:
            name: "auth-d"
            caller: src.infrastructure.callers.authorization_requests.get_request_direct_service
  - flow:
      name: fondos
      steps:
        - step:
            name: "auth-d"
            caller: src.infrastructure.callers.authorization_requests.get_request_direct_service
        - step:
            name: "fondos-sf"
            caller: src.infrastructure.callers.funds_request_caller.get_request_direct_service
  - flow:
      name: depositos
      steps:
        - step:
            name: "auth-sf"
            caller: src.infrastructure.callers.deposits_request_caller.get_request_with_sf
        - step:
            name: "depositos-sf"
            caller: src.infrastructure.callers.deposits_request_caller.get_request_security_filter
        - step:
            name: "depositos-direct"
            caller: src.infrastructure.callers.deposits_request_caller.get_request_direct_service